services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fulldemo_flask
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: company
    ports:
      - 80:80
    volumes:
      - .:/app

  mysql:
    image: mysql:latest
    container_name: fulldemo_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: company
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: fulldemo_phpmyadmin
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 8080:80

  arangodb1:
    image: arangodb:latest
    container_name: fulldemo_arangodb1
    environment:
      ARANGO_ROOT_PASSWORD: password
    volumes:
      - arangodb_data1:/var/lib/arangodb3
    ports:
      - 8529:8529

  arangodb2:
    image: arangodb:latest
    container_name: fulldemo_arangodb2
    environment:
      ARANGO_ROOT_PASSWORD: password
    volumes:
      - arangodb_data2:/var/lib/arangodb3
    ports:
      - 8530:8529

  redis:
    image: redis:latest
    container_name: fulldemo_redis
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  arangodb_data1:
  arangodb_data2:
  redis_data:
